backend:
  name: git-gateway
  branch: main
media_folder: "assets/uploads"
public_folder: "/uploads"
collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
